# Generated by Django 3.2.9 on 2021-11-18 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('insertdate', models.DateField(default=django.utils.timezone.now)),
                ('updatedate', models.DateField(default=django.utils.timezone.now)),
                ('deleteflag', models.BooleanField(default=False)),
            ],
        ),
    ]
