# Generated by Django 3.2.9 on 2021-11-20 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_m_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('title', models.TextField()),
                ('readdata', models.DateField(default=django.utils.timezone.now)),
                ('thoughts', models.TextField()),
                ('insertdate', models.DateField(default=django.utils.timezone.now)),
                ('updatedate', models.DateField(default=django.utils.timezone.now)),
                ('deleteflag', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='t_record',
            constraint=models.UniqueConstraint(fields=('username', 'title'), name='unique_T_Record'),
        ),
    ]
