# Generated by Django 3.2.9 on 2021-11-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20211120_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_record',
            old_name='readdata',
            new_name='readdate',
        ),
    ]
