# Generated by Django 3.2.8 on 2021-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
