# Generated by Django 3.2.9 on 2021-11-16 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_user_m_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_String',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('string', models.TextField()),
                ('insertdate', models.DateField(default=django.utils.timezone.now)),
                ('updatedate', models.DateField(default=django.utils.timezone.now)),
                ('deleteflag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='T_Attr',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('code', models.PositiveIntegerField(default=0)),
                ('string', models.TextField(default='')),
                ('insertdate', models.DateField(default=django.utils.timezone.now)),
                ('updatedate', models.DateField(default=django.utils.timezone.now)),
                ('deleteflag', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='m_user',
            name='deleteflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_user',
            name='insertdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='m_user',
            name='updatedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='m_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='t_attr',
            constraint=models.UniqueConstraint(fields=('id', 'code', 'string'), name='unique_stock'),
        ),
    ]
